### ISSUE TITLE
Failed to run go-chassis based application under kubernetes

### ISSUE THREAD

**Issue by crystaldust** [ServiceComb/go-chassis#213]
Hi all, I'm trying to run my go-chassis based applications in a kubernetes cluster. The individual micro-services are running in k8s pod and accessed by k8s services, so I configure the provider's `--advertiseAddress` to be the domain name(service name plus namespace in k8s). But the `advertisementAddress` is only allowed to be a CIDR IP address, according to the code around [here](https://github.com/ServiceComb/go-chassis/blob/eae8debdaac1ca2e7da27ab81d9ddc168bf45ad7/core/registry/util.go#L101), so the service cannot be registered in the service center.

As I understand(might not be correct), when a service register itself in the service center, the `--advertiseAddress` is stored and dispatched to other services to make the registering service accessible. So the address might not only be a CIDR IP, but also domain names, IPv6 address, or even Unix socket under some special situation.

Any ideas on this?

**Comment by tianxiaoliang** [comment]
go-chassis don't depend on k8s service, but only depend on container network, to avoid user misusing, we only allow CIDR IP in adveriseAddress
the domain you talked about is k8s service name, behind this dns name，it has more than one a record, so it is not allowed, because loadbalancing is embedded in go chassis .

We will write doc to clarify it

**Comment by crystaldust** [comment]
Thanks, looking forward to the docs

**Comment by crystaldust** [comment]
Thanks, I followed the docs, comment the `--advertiseAddress` and set `listenAddress` to be '0.0.0.0:8080', it works!
